---
title: "Using Natural Language Processing (NLP) to Implement Sentiment Analysis and Keyword Extraction on Yale Course Evaluations"
author: "Alexander Abinader"
date: "2024-02-26"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

TODO

# Background

Natural language processing (NLP) is a modern technology that allows computers to interpret and manipulate human language. The NLP field has experienced explosive growth in the past several years, mainly due to its vast number of important applications. Popular technologies like speech recognition, email filtering, chatbots, predictive text, and many others rely heavily on NLP techniques, making it a highly sought after skill for programmers and data scientists worldwide.\\
\indent Two of the most popular NLP areas include sentiment analysis and keyword extraction. Sentiment analysis is an extremely valuable procedure that allows computers to evaluate written text through a human lens. For example, there exist many pretrained sentiment analysis models that have been used for a variety of popular applications such as evaluating Amazon product reviews or rating the sentiment of social media posts such as those on Twitter (now X).\\
\indent Keyword extraction is a separate technique that automatically identifies the key words that summarize the main topics of a written text. A similar process called topic modeling also seeks to identify the key terminology present in text but goes one step further to identify what underlying themes these words represent. Generally, in the context of shorter written pieces (a few words to a short paragraph), keyword extraction proves more effective at identifying terms of interest.

# Introduction

At the end of each semester, Yale students are given optional surveys to complete where they review their classes for that term. Within these surveys are sets of questions that provide five multiple choice responses. For example, one of the most important questions is ``What is your overall assessment of this course?" to which students can reply with `poor', `fair', `good', `very good', or `excellent'. Notably, this type of question and its discrete set of responses can be converted into a numerical score. This facilitates the process of creating summary statistics for course evaluations using this quantitative data. A student created, student run website named CourseTable does just that.\\
\indent CourseTable is a course review website that serves the Yale community by providing information about Yale classes. In addition to official registrar data like class enrollment size, professor, location, etc., CourseTable also uses the official end of semester surveys that students fill out in order to publish a host of descriptive statistics and reviews for Yale's thousands of courses. Namely, CourseTable uses the responses from the multiple choice survey questions about course overview, intellectual challenge, workload, and others in order to create three quantitative ratings: Average Course Rating, Average Workload Rating, and Average Professor Rating.\\
\indent In addition to multiple choice survey questions, Yale's official end of semester surveys also provide room for written responses, free from any constraints. This data is presented on CourseTable in its raw form. No analysis is performed on these written responses. CourseTable simply lists the questions that were asked in the registrar survey and then prints the entire set of student responses. Analyzing this textual data is just the task for NLP.

# Data Collection

Cite CourseTable, discuss using Python to make the API call with cookie authentication. Also, how I narrowed down the courses
that I would get reviews for.

# Data Cleaning

Not much. Discuss lemmatization and tokenization although this is auto handled by pretty much all of the packages.

# Sentiment Analysis

## Pretrained

### TextBlob

~65%

### VADER

~75%

### RoBERTa

~77%

## Trained Models

### Logistic Regression

### Support Vector Machine

~84%

### Random Forest

~74%

### Neural Network

# Keyword Extraction

# Dashboard

# Conclusion






